### ISSUE TITLE
fela-plugin-prefixer does not work with React

### ISSUE THREAD

**Issue by IgorBabkin** [robinweser/fela#740]
**Type**: Bug

| Packages | Version |
| ---------- | ------- |
| fela          | 10.7.0   |
| react-fela | 10.7.0   |
| fela-plugin-prefixer | 10.7.0   |
| react        | 16.9.0   |

-------------------
#### Description
Plugin cuts style properties which must be prefixed.

#### Expected Behavior
```javascript
import {render} from 'react-dom';
import {createRenderer} from "fela";
import prefixer from "fela-plugin-prefixer";
import {RendererProvider, useFela} from 'react-fela';
import * as React from 'react';
import {FunctionComponent} from 'react';

const renderer = createRenderer({
    plugins: [prefixer()]
});

const controlStyle = () => ({
    backgroundImage: 'linear-gradient(0deg, rgba(0, 0, 0, 0.35) 0%, rgba(0, 0, 0, 0.2) 70%, rgba(0, 0, 0, 0) 90%)',
    display: 'flex',
    color: 'red',
});

export const Control: FunctionComponent = () => {
    const {css} = useFela();
    return (
        <div className={css(controlStyle)}/>
    );
};


render(
    <RendererProvider renderer={renderer}>
        <Control/>
    </RendererProvider>,
    document.getElementById('root'),
);

```

#### Actual Behavior
```javascript
<div class="a b c"></div>

// where .c { color: red; }, .b {}, .a {}
```

**Comment by robinweser** [comment]
Hey there,
As stated in the plugin [docs](https://github.com/robinweser/fela/tree/master/packages/fela-plugin-prefixer#fela-plugin-prefixer): The plugin requires the [fela-plugin-fallback-value](https://github.com/robinweser/fela/tree/master/packages/fela-plugin-fallback-value) to be added after it in order to work properly. Also, I would recommend using [fela-preset-web](https://github.com/robinweser/fela/tree/master/packages/fela-preset-web) anyways!

Hope this helps :)
