### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by marwan38** [robinweser/fela#919]
**Type**: Question

| Packages | Version |
| -------- | ------- |
| fela     | 12.x.x  |

---

#### Description

Debugging fela is extremely difficult and time consuming. Unfortunately we've built a not so small project on fluentui which internally uses fela. All class names are: a, b, c, etc.... which make it very difficult and troublesome to debug in development WHERE classes are coming from. I can't find anything within the documentation to make it a little bit easier to debug.

Has this issue been solved already? are there plugins to get around this? In my desperation I looked around and started to "cook" a solution which includes a compile time transfomer to transform styles and inject the _className property that i noticed in `extractCustomClassName`. This solution is only half of a solution as the resulting class names don't include styles, and are just there for reference. 

To clarify, I want to not break up properties into their own classes to help us at least track down where a certain style is coming from. From my understanding, this is the very least we can achieve with how fela is set up and works.

#### Steps to reproduce

N/A

#### Expected Behavior

N/A
#### Actual Behavior

N/A

#### Proposal

N/A

**Comment by robinweser** [comment]
Hmm, what's your use case? You usually do not debug the generated CSS as it exactly reflects the written code.
With atomic CSS classes do not come from a certain component, but are reused all over the app in a one-to-many relation.
You can always pass custom HTML attributes including className, if you want to pin down a component, otherwise I'd rather debug the style object(s) that you pass to components directly, to see which styles are applied.

**Comment by robinweser** [comment]
Closing this. Feel free to open a discussion if you want to further discuss the topic!
